# GitHub CLI configuration
git_protocol: https
editor: nvim
prompt: enabled
pager: less
browser:
aliases:
    co: pr checkout
    pv: pr view
    pc: pr create
    pl: pr list
    il: issue list
    iv: issue view
    ic: issue create
version: "1"
